openapi: 3.0.3
info:
  title: Voice-Controlled PC Assistant WebSocket API
  description: Real-time WebSocket API for voice command processing and PC control
  version: 1.0.0
  contact:
    name: PC Control Voice Assistant Team
  license:
    name: MIT

servers:
  - url: ws://localhost:8765/ws
    description: Development server
  - url: wss://pc.local:8765/ws
    description: Production server with mTLS

# WebSocket message schemas
components:
  schemas:
    # Base message types
    BaseMessage:
      type: object
      required:
        - type
        - id
        - timestamp
      properties:
        type:
          type: string
          description: Message type identifier
        id:
          type: string
          format: uuid
          description: Unique message identifier
        timestamp:
          type: string
          format: date-time
          description: Message timestamp (UTC)

    # Connection management
    ConnectionRequest:
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - type: object
          required:
            - authentication_token
            - device_fingerprint
          properties:
            type:
              const: "connection_request"
            authentication_token:
              type: string
              description: JWT authentication token
            device_fingerprint:
              type: string
              description: Android device certificate fingerprint
            pc_info:
              type: object
              properties:
                name:
                  type: string
                ip_address:
                  type: string
                  format: ipv4
                mac_address:
                  type: string
                  format: mac

    ConnectionResponse:
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - type: object
        required:
            - status
          properties:
            type:
              const: "connection_response"
            status:
              type: string
              enum: ["authenticated", "error", "rejected"]
            session_id:
              type: string
              format: uuid
              description: Session identifier for authenticated connections
            error_code:
              type: string
              enum: ["invalid_token", "device_not_paired", "certificate_mismatch", "server_error"]
            error_message:
              type: string
              description: User-friendly error message in Turkish

    # Audio streaming
    AudioData:
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - type: object
        required:
          - sequence_number
          - audio_chunk
          - sample_rate
          - channels
        properties:
          type:
            const: "audio_data"
          sequence_number:
            type: integer
            minimum: 0
            description: Sequential packet number for ordering
          audio_chunk:
            type: string
            format: byte
            description: Opus-encoded audio chunk
          sample_rate:
            type: integer
            enum: [16000]
            description: Audio sample rate in Hz
          channels:
            type: integer
            enum: [1]
            description: Number of audio channels
          is_final:
            type: boolean
            description: True if this is the final chunk of the audio stream

    # Voice command processing
    VoiceCommand:
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - type: object
        required:
          - transcription
          - confidence
          - language
        properties:
          type:
            const: "voice_command"
          transcription:
            type: string
            maxLength: 1000
            description: Turkish transcription with embedded English terms
          confidence:
            type: number
            minimum: 0.0
            maximum: 1.0
            description: STT confidence score
          language:
            type: string
            enum: ["tr"]
            description: Primary language code
          duration_ms:
            type: integer
            minimum: 100
            maximum: 30000
            description: Audio duration in milliseconds

    # Status updates
    CommandStatus:
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - type: object
        required:
          - command_id
          - status
        properties:
          type:
            const: "command_status"
          command_id:
            type: string
            format: uuid
            description: Voice command identifier
          status:
            type: string
            enum: ["dinliyor", "işleniyor", "çalıştırılıyor", "tamamlandı", "hata"]
            description: Turkish status messages for user display
          progress_percentage:
            type: number
            minimum: 0
            maximum: 100
            description: Progress percentage for long-running operations
          estimated_remaining_ms:
            type: integer
            description: Estimated remaining time in milliseconds

    # Action execution
    ActionExecution:
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - type: object
        required:
          - command_id
          - action_id
          - action_type
          - status
        properties:
          type:
            const: "action_execution"
          command_id:
            type: string
            format: uuid
          action_id:
            type: string
            format: uuid
          action_type:
            type: string
            enum: [
              "system_launch", "system_volume", "system_file_find",
              "system_info", "system_file_delete", "browser_navigate",
              "browser_search", "browser_extract", "browser_interact"
            ]
          status:
            type: string
            enum: ["pending", "executing", "completed", "failed", "requires_confirmation"]
          parameters:
            type: object
            description: Action-specific parameters (see schemas below)
          result:
            type: object
            description: Action execution result
          error_code:
            type: string
            description: Machine-readable error code
          error_message:
            type: string
            description: User-friendly error message in Turkish

    # System operation parameters
    SystemLaunchParams:
      type: object
      required:
        - application_name
      properties:
        application_name:
          type: string
          description: Application name (e.g., "Chrome", "Notepad")
        arguments:
          type: string
          description: Optional command line arguments

    SystemVolumeParams:
      type: object
      required:
        - level
      properties:
        level:
          type: integer
          minimum: 0
          maximum: 100
          description: Volume level (0-100)
        relative:
          type: boolean
          description: True for relative change (+/-), false for absolute

    SystemFileFindParams:
      type: object
      required:
        - pattern
      properties:
        pattern:
          type: string
          description: File name or search pattern
        search_paths:
          type: array
          items:
            type: string
          description: Directories to search (default: user directories)

    SystemFileDeleteParams:
      type: object
      required:
        - file_path
      properties:
        file_path:
          type: string
          format: uri
          description: Full file path to delete
        confirmation:
          type: boolean
          description: User confirmation flag for system directories

    # Browser operation parameters
    BrowserNavigateParams:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri
          description: URL to navigate to

    BrowserSearchParams:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: Search query
        search_engine:
          type: string
          enum: ["google", "bing", "duckduckgo"]
          default: "google"
          description: Search engine to use

    # Action results
    ActionResult:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
          description: Result description in Turkish
        data:
          type: object
          description: Action-specific result data
        execution_time_ms:
          type: integer
          description: Action execution time

    FileSearchResult:
      type: object
      properties:
        files:
          type: array
          items:
            type: object
            properties:
              path:
                type: string
              name:
                type: string
              size:
                type: integer
              modified_date:
                type: string
                format: date-time
        total_count:
          type: integer
        search_time_ms:
          type: integer

    SystemInfoResult:
      type: object
      properties:
        os_version:
          type: string
        cpu_usage:
          type: number
        memory_usage:
          type: object
          properties:
            total_gb:
              type: number
            used_gb:
              type: number
            percentage:
              type: number
        disk_usage:
          type: array
          items:
            type: object
            properties:
              drive:
                type: string
              total_gb:
                type: number
              used_gb:
                type: number
              percentage:
                type: number

    # Error responses
    ErrorResponse:
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - type: object
        required:
          - error_code
          - error_message
        properties:
          type:
            const: "error"
          error_code:
            type: string
            enum: [
              "authentication_failed", "invalid_message_format",
              "audio_processing_error", "stt_service_unavailable",
              "llm_service_unavailable", "action_execution_failed",
              "network_error", "server_error", "rate_limit_exceeded"
            ]
          error_message:
            type: string
            description: User-friendly error message in Turkish
          retry_after_ms:
            type: integer
            description: Suggested retry delay in milliseconds
          details:
            type: object
            description: Additional error details for debugging

    # Wake-on-LAN
    WakeOnLANRequest:
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - type: object
        required:
          - mac_address
          - ip_address
        properties:
          type:
            const: "wake_on_lan"
          mac_address:
            type: string
            format: mac
            description: Target PC MAC address
          ip_address:
            type: string
            format: ipv4
            description: Broadcast IP address
          port:
            type: integer
            default: 9
            description: WoL port number

    WakeOnLANResponse:
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - type: object
        required:
          - status
        properties:
          type:
            const: "wake_on_lan_response"
          status:
            type: string
            enum: ["sent", "failed", "already_awake"]
          message:
            type: string
            description: Status message in Turkish

# WebSocket connection lifecycle
paths:
  /ws:
    get:
      summary: WebSocket connection endpoint
      description: Establishes WebSocket connection for real-time communication
      tags:
        - Connection
      responses:
        '101':
          description: WebSocket connection established
        '401':
          description: Authentication required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Device not paired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

tags:
  - name: Connection
    description: Connection management and authentication
  - name: Audio
    description: Audio streaming and voice command processing
  - name: Actions
    description: System and browser action execution
  - name: Status
    description: Status updates and progress reporting
  - name: Errors
    description: Error handling and recovery

# Message flow examples
examples:
  ConnectionExample:
    summary: Authentication handshake
    value:
      type: "connection_request"
      id: "550e8400-e29b-41d4-a716-446655440000"
      timestamp: "2025-11-18T10:30:00Z"
      authentication_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      device_fingerprint: "a1:b2:c3:d4:e5:f6"
      pc_info:
        name: "Ev PC"
        ip_address: "192.168.1.100"
        mac_address: "00:11:22:33:44:55"

  AudioStreamExample:
    summary: Audio data chunk
    value:
      type: "audio_data"
      id: "550e8400-e29b-41d4-a716-446655440001"
      timestamp: "2025-11-18T10:30:01Z"
      sequence_number: 0
      audio_chunk: "OpusEncodedBinaryData..."
      sample_rate: 16000
      channels: 1
      is_final: false

  VoiceCommandExample:
    summary: Processed voice command
    value:
      type: "voice_command"
      id: "550e8400-e29b-41d4-a716-446655440002"
      timestamp: "2025-11-18T10:30:02Z"
      transcription: "Chrome'u aç"
      confidence: 0.95
      language: "tr"
      duration_ms: 1500

  StatusUpdateExample:
    summary: Command status update
    value:
      type: "command_status"
      id: "550e8400-e29b-41d4-a716-446655440003"
      timestamp: "2025-11-18T10:30:03Z"
      command_id: "550e8400-e29b-41d4-a716-446655440002"
      status: "çalıştırılıyor"

  ActionExecutionExample:
    summary: System action execution
    value:
      type: "action_execution"
      id: "550e8400-e29b-41d4-a716-446655440004"
      timestamp: "2025-11-18T10:30:04Z"
      command_id: "550e8400-e29b-41d4-a716-446655440002"
      action_id: "660e8400-e29b-41d4-a716-446655440000"
      action_type: "system_launch"
      status: "completed"
      parameters:
        application_name: "Chrome"
      result:
        success: true
        message: "Chrome başarıyla açıldı"
        execution_time_ms: 1200